[package]
name = "generate"
version = "0.0.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
anyhow = "1.0"
clap = { version = "*", features = ["string"] }
clap_complete = "4.5.6"
clap_mangen = "0.2.22"
reddish-shift = { path = "../../" }

[lints]
workspace = true
