[package]
name = "reddish-shift"
version = "0.0.0"
edition = "2021"
authors = ["Mahor Foruzesh <mahor1221@gmail.com>"]

[[bin]]
path = "src/redshift.rs"
name = "redshift"

[dependencies]
libc = "0.2"
x11-dl = "2.21.0"
xcb = { version = "1.4.0", features = ["randr"] }

drm-rs = "0.1.3"
gio-sys = "0.19.5"
glib-sys = "0.19.5"
gobject-sys = "0.19.5"
