[package]
name = "reddish-shift"
version = "0.0.0"
edition = "2021"
authors = ["Mahor Foruzesh <mahor1221@gmail.com>"]
license = "GPL-3.0-or-later"
description = "Set color temperature of display according to time of day"
repository = "https://github.com/mahor1221/reddish-shift"
readme = "README.md"
build = "build.rs"

[dependencies]
thiserror = "1.0.61"
const_format = "0.2.32"
anyhow = "1.0.86"
frunk = "0.4"
frunk_core = "0.4"

chrono = "0.4.38"
x11rb = { version = "0.13.1", features = ["xf86vidmode", "randr"] }
drm = "0.12.0"
# required for location_geoclue2.rs
#libc = "0.2"
#gio-sys = "0.18.1"
#glib-sys = "0.18.1"
#gobject-sys = "0.18.0"

# cli
clap = { version = "4.5.7", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
anstream = "0.6.14"
anstyle = "1.0.7"
exitcode = "1.1.2"
ctrlc = { version = "3.4.4", features = ["termination"] }

# config
dirs = "5.0.1"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "8.3", features = ["cargo", "git", "gitcl", "rustc"] }
[dev-dependencies]
insta = "1.39.0"

[profile.release]
lto = true
strip = true
codegen-units = 1
[profile.ci]
inherits = "dev"
debug = false
[profile.perf]
inherits = "release"
strip = false
debug = 1

[lints.rust]
unsafe_code = "forbid"
[lints.rustdoc]
private-doc-tests = "warn"
unescaped-backticks = "warn"
[lints.clippy]
panic = "deny"
dbg-macro = "warn"
decimal-literal-representation = "warn"
expect-used = "deny"
explicit-auto-deref = "warn"
get-unwrap = "warn"
manual-let-else = "warn"
missing-enforced-import-renames = "warn"
obfuscated-if-else = "warn"
semicolon-outside-block = "warn"
todo = "warn"
too-many-lines = "warn"
undocumented-unsafe-blocks = "deny"
unimplemented = "warn"
uninlined-format-args = "warn"
unnested-or-patterns = "warn"
unwrap-in-result = "warn"
unwrap-used = "warn"
use-debug = "warn"
