[package]
name = "reddish-shift"
version = "0.0.0"
edition = "2021"
authors = ["Mahor Foruzesh <mahor1221@gmail.com>"]
license = "GPL-3.0-or-later"
build = "build.rs"

[[bin]]
path = "src/reddish-shift.rs"
name = "reddish-shift"

[dependencies]
libc = "0.2"
x11-dl = "2.21"
xcb = { version = "1.4", features = ["randr"] }
drm-rs = "0.1"
gio-sys = "0.18.1"
glib-sys = "0.18.1"
gobject-sys = "0.18.0"

anyhow = "1.0"
const_format = "0.2"

dirs = "5.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
time = { version = "0.3.36", features = ["local-offset"] }

[build-dependencies]
anyhow = "1.0"
vergen = { version = "8.3", features = ["cargo", "git", "gitcl", "rustc"] }

[profile.release]
lto = true
strip = true
codegen-units = 1

[profile.ci]
inherits = "dev"
debug = false

[profile.perf]
inherits = "release"
strip = false
debug = 1

# [lints.rust]
# unsafe_code = "forbid"
[lints.rustdoc]
private-doc-tests = "warn"
unescaped-backticks = "warn"
[lints.clippy]
# panic = "deny"
dbg-macro = "warn"
decimal-literal-representation = "warn"
# expect-used = "deny"
explicit-auto-deref = "warn"
get-unwrap = "warn"
manual-let-else = "warn"
missing-enforced-import-renames = "warn"
obfuscated-if-else = "warn"
semicolon-outside-block = "warn"
todo = "warn"
too-many-lines = "warn"
# undocumented-unsafe-blocks = "deny"
unimplemented = "warn"
uninlined-format-args = "warn"
unnested-or-patterns = "warn"
unwrap-in-result = "warn"
unwrap-used = "warn"
use-debug = "warn"
