[package]
name = "reddish-shift"
version = "0.0.0"
edition = "2021"
authors = ["Mahor Foruzesh <mahor1221@gmail.com>"]

[[bin]]
path = "src/redshift.rs"
name = "redshift"

[dependencies]
libc = "0.2"
x11-dl = "2.21.0"
xcb = { version = "1.4.0", features = ["randr"] }

drm-rs = "0.1.3"
gio-sys = "0.19.5"
glib-sys = "0.19.5"
gobject-sys = "0.19.5"

[profile.release]
lto = true
strip = true
codegen-units = 1

[profile.ci]
inherits = "dev"
debug = false

[profile.perf]
inherits = "release"
strip = false
debug = 1

# [lints.rust]
# unsafe_code = "forbid"

[lints.rustdoc]
private-doc-tests = "warn"
unescaped-backticks = "warn"

[lints.clippy]
# panic = "deny"
dbg-macro = "warn"
decimal-literal-representation = "warn"
# expect-used = "deny"
explicit-auto-deref = "warn"
get-unwrap = "warn"
manual-let-else = "warn"
missing-enforced-import-renames = "warn"
obfuscated-if-else = "warn"
semicolon-outside-block = "warn"
todo = "warn"
too-many-lines = "warn"
# undocumented-unsafe-blocks = "deny"
unimplemented = "warn"
uninlined-format-args = "warn"
unnested-or-patterns = "warn"
unwrap-in-result = "warn"
unwrap-used = "warn"
use-debug = "warn"
