# Set the day and night screen temperatures
temperature = "5700-3500"

# Set the screen brightness. Default is 1.0.
#brightness = "0.9"
# It is also possible to use different settings for day and night
#brightness = "0.7-0.4"

# Set the screen gamma (for all colors, or each color channel individually)
gamma = "0.8"
#gamma = "0.8:0.7:0.8"
# This can also be set individually for day and night
#gamma = "0.8:0.7:0.8 - 0.6"
#gamma = "0.8:0.7:0.8 - 0.6:0.5:0.6"

# Whether to preserve gamma ramps if supported by gamma method.
#preserve_gamma = true

# Disable the smooth fade between temperatures when Reddish Shift starts and
# stops. false will cause an immediate change between screen temperatures. true
# will gradually apply the new screen temperature over a couple of seconds.
fade = true

# Set transition scheme: 'time-ranges', 'elevation'
# Setting it to `elevation` requires using a location provider
transition-scheme = "elevation"

# Solar elevation thresholds.
# By default, Reddish Shift will use the current elevation of the sun to
# determine whether it is daytime, night or in transition (dawn/dusk). When
# the sun is above the degrees specified with elevation-high it is considered
# daytime and below elevation-low it is considered night.
#elevation.high = 3
#elevation.low= -6

# Custom dawn/dusk ranges.
# Instead of using the solar elevation, the time ranges of dawn and dusk can
# be specified manually. The times must be specified as HH:MM in 24-hour format.
#time-ranges.dawn = "6:00-7:45"
#time-ranges.dusk = "18:35-20:15"

# Set the location-provider: 'geoclue2', 'manual'
# type 'reddish-shift -l list' to see possible values.
location-provider = "manual"

# Configuration of the location-provider:
# type 'reddish-shift -l PROVIDER:help' to see the settings.
# ex: 'reddish-shift -l manual:help'
# Keep in mind that longitudes west of Greenwich (e.g. the Americas)
# are negative numbers.
manual.latitude = 48.1
manual.longitude = 11.6

# Set the adjustment-method: 'randr', 'vidmode', 'drm'
# type 'reddish-shift -m list' to see all possible values.
# 'randr' is the preferred method, 'vidmode' is an older API. but works in some
# cases when 'randr' does not.
adjustment-method = "randr"

# Configuration of the adjustment-method
# type 'reddish-shift -m METHOD:help' to see the settings.
# ex: 'reddish-shift -m randr:help'
# In this example, randr is configured to adjust only screen 0. Note that the
# numbering starts from 0, so this is actually the first screen. If this option
# is not specified, Reddish Shift will try to adjust _all_ screens.
randr.screen = 0
