# Color temperature to set for day and night [default: 6500-4500]

# The neutral temperature is 6500K. Using this value will not change the color
# temperature of the display. Setting the color temperature to a value higher
# than this results in more blue light, and setting a lower value will result
# in more red light.
#temperature = 5000        #(day=night=5000)
#temperature = "6500-4500" #(day=6500, night=4500)
temperature = "4600-3600"

# Additional gamma correction to apply for day and night [default: 1.0]
#
# Either set it for all colors, or each color channel individually
#gamma = 0.9                 #(day=night=0.9)
#gamma = "1.0 - 0.8:0.9:0.9" #(day=1.0, night=(R=0.8, G=0.9, B=0.9))
gamma = "0.9:0.9:0.9 - 0.85:0.9:0.9"

# Screen brightness to apply for day and night [default: 1.0]
#
# It is a fake brightness adjustment obtained by manipulating the gamma ramps
# which means that it does not reduce the backlight of the screen
#brightness = 1.0       #(day=night=0.8)
#brightness = "1.0-0.8" #(day=1.0, night=0.8)


# Transition scheme [default: 3:-6]
#
# Either time ranges or elevation angles. By default, Reddish Shift will use
# the current elevation of the sun to determine whether it is daytime, night
# or in transition (dawn/dusk). You can also use the print command to see solar
# elevation angles for the next 24 hours
#scheme = "6:00-7:45 - 18:35-20:15" #(dawn=6:00-7:45, dusk=18:35-20:15)
#scheme = "7:45 - 18:35"            #(day starts at 7:45, night starts at 20:15)
#scheme = "3:-6"                    #(above 3° is day, bellow -6° is night)


# Location, used for computation of current solar elevation [default: 0:0]
#
# It is not needed when using manual time ranges for transition scheme Either
# set latitude and longitude manually or select a location provider. Negative
# values represent west and south, respectively.
#location = "51.48:0.0" #(Greenwich)
#location = "geoclue2"  #(Currently not available)


# Adjustment method to use to apply color settings
#
# If not set, the first available method will be used
#method = dummy                 #(does not affect the display)
# XVidMode extension
#method = "vidmode"             #(apply to $DISPLAY)
#method = "vidmode:0"           #(apply to screen 0)
# XRANDR extension
#method = "randr"               #(apply to $DISPLAY)
#method = "randr:0"             #(apply to screen 0)
#method = "randr$DISPLAY:62,63" #(apply to $DISPLAY with crtcs 62 and 63)
# Direct Rendering Manager
#method = "drm"                 #(apply to /dev/dri/card0)
#method = "drm:1"               #(apply to /dev/dri/card1)
#method = "drm:0:80"            #(apply to /dev/dri/card0 with crtc 80)
# Windows graphics device interface:
#method = "win32gdi"            #(apply to current display)


# Reset existing gamma ramps before applying new color settings
#reset-ramps = false


# Disable fading between color temperatures
#
# It will cause an immediate change between screen temperatures. by default,
# the new screen temperature are gradually applied over a
# couple of seconds
#disable-fade = false


# Duration of sleep between screen updates in milliseconds
#sleep-duration = 5000


# Duration of sleep between screen updates for fade in milliseconds
#sleep-duration_short = 100
