
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.camino]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.cargo-platform]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.config]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.const_format]]
version = "0.2.32"
criteria = "safe-to-deploy"

[[exemptions.const_format_proc_macros]]
version = "0.2.32"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.11"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.drm-rs]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.gio-sys]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.glib-sys]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.gobject-sys]]
version = "0.18.0"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.num-conv]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.num_threads]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.pathdiff]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.system-deps]]
version = "6.2.2"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.36"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.18"
criteria = "safe-to-deploy"

[[exemptions.vergen]]
version = "8.3.1"
criteria = "safe-to-deploy"

[[exemptions.version-compare]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.x11-dl]]
version = "2.21.0"
criteria = "safe-to-deploy"

[[exemptions.xcb]]
version = "1.4.0"
criteria = "safe-to-deploy"
