name: CICD

on:
  pull_request:
  push:
    branches:
    - main
  release:
    types: [created]
  # create:
  #   tags:
  #   - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  PKG_NAME: reddish-shift
  CARGO_TERM_COLOR: always
  # RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest
    permissions:
      # required for ppremk/lfs-warning
      pull-requests: read
      # required for LouisBrunner/checks-action
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-on-failure: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: typos,cargo-deny

      - name: Check spelling
        if: success() || failure()
        id: typos
        run: typos

      - name: Check dependencies
        if: success() || failure()
        id: cargo-deny
        run: cargo deny check

      - name: Check formatting
        if: success() || failure()
        id: cargo-fmt
        run: cargo fmt --all -- --check

      - name: Check build
        if: success() || failure()
        id: cargo-check
        run: cargo check --profile=ci

      - name: Check lints
        if: success() || failure()
        id: cargo-clippy
        run: cargo clippy --profile=ci

      - name: Check tests
        if: success()
        id: cargo-test
        run: cargo test --profile=ci

      - name: Check documents
        if: success()
        id: cargo-doc
        run: cargo doc --profile=ci

      # create check runs for pull requests

      - name: Check file size
        if: (success() || failure()) && github.event_name == 'pull_request'
        id: lfs
        uses: mahor1221/lfs-warning@master
        with:
          filesizelimit: 256000
          sendComment: false

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check file size
          conclusion: ${{ steps.lfs.outcome }}

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check spelling
          conclusion: ${{ steps.typos.outcome }}

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check dependencies
          conclusion: ${{ steps.cargo-deny.outcome }}

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check formatting
          conclusion: ${{ steps.cargo-fmt.outcome }}

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check build
          conclusion: ${{ steps.cargo-check.outcome }}

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check lints
          conclusion: ${{ steps.cargo-clippy.outcome }}

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check tests
          conclusion: ${{ steps.cargo-test.outcome }}

      - uses: LouisBrunner/checks-action@v2.0.0
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check documents
          conclusion: ${{ steps.cargo-doc.outcome }}

  create-release:
    name: Create release
    if: github.event_name == 'release'
    needs: run-checks
    permissions:
      # required for taiki-e/create-gh-release-action
      contents: write
    runs-on: ubuntu-latest
    outputs:
      linux-assets: >-
        target/ci/completion,
        target/ci/man1,
        assets/systemd/${{ env.PKG_NAME }}.service
      macos-assets: >-
        target/ci/completion,
        target/ci/man1
      windows-assets: >-
        target/ci/completion/_${{ env.PKG_NAME }}.ps1
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          branch: main
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    name: Build release
    needs: create-release
    permissions:
      contents: write
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            assets: ${{ needs.create-release.outputs.linux-assets }}
          - target: aarch64-unknown-linux-musl
            assets: ${{ needs.create-release.outputs.linux-assets }}
          - target: x86_64-unknown-linux-gnu
            assets: ${{ needs.create-release.outputs.linux-assets }}
          - target: x86_64-unknown-linux-musl
            assets: ${{ needs.create-release.outputs.linux-assets }}

          - target: aarch64-pc-windows-msvc
            assets: ${{ needs.create-release.outputs.windows-assets }}
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            assets: ${{ needs.create-release.outputs.windows-assets }}
            os: windows-latest

          # - target: aarch64-apple-darwin
          #   os: macos-latest
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          # - target: universal-apple-darwin
          #   os: macos-latest

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-on-failure: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin,cargo-deb

      - name: Generate code coverage reports
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      - name: Upload code coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate assets
        run: cargo build --release -p generate
      - if: matrix.os != 'windows-latest'
        run: rm target/ci/completion/_$PKG_NAME.ps1

      - name: Build debian package
        if: matrix.os == 'ubuntu-latest'
        id: deb
        run: |
          cargo deb -- --frozen --release
          arch="$(a=${{ matrix.target }} && echo "${a%%-*}")"
          name="$PKG_NAME-$GITHUB_REF_NAME-$arch.deb"
          mv target/debian/*.deb "target/debian/$name"
          echo path="target/debian/$name" >> $GITHUB_OUTPUT

      - name: Build and upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          draft: true
          bin: ${{ env.PKG_NAME }}
          target: ${{ matrix.target }}
          archive: $bin-$tag-$target
          include: LICENSE,README.md,CHANGELOG.md,config.toml,${{ matrix.assets }}
          asset: ${{ steps.deb.outputs.path }}
          checksum: sha256
          token: ${{ secrets.GITHUB_TOKEN }}
